{% set version = "0.8.0" %}

package:
  name: opencensus
  version: {{ version }}

source:
  url: https://github.com/census-instrumentation/opencensus-python/archive/v{{ version }}.zip
  sha256: 96b512993318e848212298c8d276eca894670507ad8bc9c33b99e430c6fe69f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - opencensus-context ==0.1.2
    - google-api-core >=1.0.0, <2.0.0

test:
  imports:
    - opencensus

about:
  home: https://github.com/census-instrumentation/opencensus-python
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenCensus - A stats collection and distributed tracing framework
  description: |
    OpenCensus makes getting critical telemetry out of your services easy and seamless.
    OpenCensus currently provides libraries for a number of languages that allow you to capture,
    manipulate, and export metrics and distributed traces to the backend(s) of your choice.
    OpenCensus works great with all software systems, from client applications, large monoliths,
    or highly-distributed microservices.
    OpenCensus started at Google but is now developed by a broad community of service
    developers, cloud vendors, and community contributors.
    OpenCensus isn’t tied to any particular vendor’s backend or analysis system.
    This is OpenCensus for Python.
  doc_url: https://opencensus.io/quickstart/python/
  dev_url: https://github.com/census-instrumentation/opencensus-python

extra:
  recipe-maintainers:
    - basnijholt
    - dhirschfeld
